---
title: "ist yazılım"
author: "Selin güler"
date: "07 01 2021"
output: pdf_document
---

```{r}
library(jsonlite)

df1<-fromJSON("C:/Users/asus/Downloads/clinical.cases_selection.2021-01-07.json")

df2<-fromJSON("C:/Users/asus/Downloads/biospecimen.cases_selection.2021-01-07.json")
df3<-fromJSON("C:/Users/asus/Downloads/mutations.2021-01-07.json")

df4<-fromJSON("C:/Users/asus/Downloads/genes.2021-01-07.json")

head(df)

```

```{r}
library(dplyr)
```

```{r}
df1$demographic = mutate(df1$demographic,hastalıkyas = case_when(df1$demographic$age_at_index<=17~"Ergen yaş aralığı",
df1$demographic$age_at_index>18 & df1$demographic$age_at_index<=65~"Genç yaş aralığı",
df1$demographic$age_at_index>66 & df1$demographic$age_at_index<=79~"Orta yaş aralığı",
df1$demographic$age_at_index>80 & df1$demographic$age_at_index<=99~"Yaşlı",
is.na(df1$demographic$age_at_index==TRUE)~NA_character_))


summary(df1$demographic$age_at_index)
table(df1$demographic$age_at_index)




table(df1$demographic$hastalıkyas)






fjfjgfjkgfkmgkmgkmhkm
şalsmşalmfdmsldfmşsldmfşsldmgşdlfmgdlkfngdf
```

```{r}
#bi daha deniyim
```

